### ISSUE TITLE
Error while publishing a NPM package to Github

### ISSUE THREAD

**Issue by devbyray** [simenandre/publish-with-yarn#5]
I'm using your action to publish a NPM package with Yarn, but I get this error. I don't know if I'm missing something 😅.

So I hope you can help me. This is the error:

```bash
Run simenandre/publish-with-yarn@v1
  with:
    npm-auth-token: ***
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Run npm version --allow-same-version --no-commit-hooks --no-git-tag-version from-git
  npm version --allow-same-version --no-commit-hooks --no-git-tag-version from-git
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
  
npm ERR! code 1[2](https://github.com/devbyray/future-ui/actions/runs/6961876462/job/18944403710#step:6:2)8
npm ERR! An unknown git error occurred
npm ERR! command /usr/bin/git --no-replace-objects describe --tags --abbrev=0 --match=*.*.*
npm ERR! fatal: No names found, cannot describe anything.

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/202[3](https://github.com/devbyray/future-ui/actions/runs/6961876462/job/18944403710#step:6:3)-11-22T19_28_16_69[4](https://github.com/devbyray/future-ui/actions/runs/6961876462/job/18944403710#step:6:4)Z-debug-0.log
Error: Process completed with exit code 12[8](https://github.com/devbyray/future-ui/actions/runs/6961876462/job/18944403710#step:6:9).
```

This is how my `yarn-publish-github-package.yml` file looks like:

```yml
name: Node.js Package on Github

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - name: Install dependencies 📦️
        run: yarn install

      - name: Build 🔨
        run: yarn build

      - uses: simenandre/publish-with-yarn@v1
        with:
          npm-auth-token: ${{ secrets.GITHUB_TOKEN }}
```
